-- ============================================================================
-- SE-Console — initial schema (V1)
--
-- Creates the four operational tables described in Foundation Guide §7.2
-- and seeds a default administrator account.
--
-- Seeded admin:
--   username : admin
--   password : changeme
--   role     : admin
--   must_change_password : TRUE  (user is forced to change on first login)
--
-- The password hash below is BCrypt, cost 10, salt "MxGo3PPzMCTejV/9M1Xt8O".
-- It is reproducible: any BCryptPasswordEncoder with strength 10 will match
-- "changeme" against this hash. Do NOT use this hash in any other context.
--
-- NOTE ON H2 SYNTAX
-- This file is PostgreSQL-compatible; H2 in compatibility mode understands it.
-- If we ever migrate to Postgres, only the AUTO_INCREMENT keyword below needs
-- to change to GENERATED BY DEFAULT AS IDENTITY.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                    BIGINT        AUTO_INCREMENT PRIMARY KEY,
    username              VARCHAR(64)   NOT NULL UNIQUE,
    password_hash         VARCHAR(120)  NOT NULL,          -- BCrypt, ~60 chars
    role                  VARCHAR(16)   NOT NULL,          -- admin | operator | viewer
    status                VARCHAR(16)   NOT NULL DEFAULT 'active',  -- active | disabled
    must_change_password  BOOLEAN       NOT NULL DEFAULT FALSE,
    last_login_at         TIMESTAMP,
    last_login_ip         VARCHAR(64),
    failed_login_count    INT           NOT NULL DEFAULT 0,
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by            BIGINT        REFERENCES users(id)
);

CREATE INDEX idx_users_status ON users(status);


-- ---------------------------------------------------------------------------
-- audit_entries
-- Append-only log of user actions. NEVER updated or deleted before retention.
-- ---------------------------------------------------------------------------
CREATE TABLE audit_entries (
    id            BIGINT       AUTO_INCREMENT PRIMARY KEY,
    event_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id       BIGINT,                     -- may be NULL for failed logins
    username      VARCHAR(64),                -- denormalized for deleted users
    action        VARCHAR(64)  NOT NULL,      -- e.g. LOGIN, START_CHANNEL, UPDATE_CONFIG
    target_type   VARCHAR(32),                -- channel | config | user
    target_id     VARCHAR(128),               -- ch-outbound-04, channel.conf, etc.
    result        VARCHAR(16)  NOT NULL,      -- success | failed
    details_json  CLOB,                       -- JSON: { before, after, reason }
    source_ip     VARCHAR(64),
    user_agent    VARCHAR(512)
);

CREATE INDEX idx_audit_time   ON audit_entries(event_time DESC);
CREATE INDEX idx_audit_user   ON audit_entries(user_id);
CREATE INDEX idx_audit_action ON audit_entries(action);


-- ---------------------------------------------------------------------------
-- config_versions
-- Full content of every applied config version. Append-only; rollback creates
-- a NEW row (never deletes), so audit integrity is preserved.
-- ---------------------------------------------------------------------------
CREATE TABLE config_versions (
    id                        BIGINT        AUTO_INCREMENT PRIMARY KEY,
    file_name                 VARCHAR(128)  NOT NULL,
    version                   INT           NOT NULL,
    content                   CLOB          NOT NULL,
    content_sha               VARCHAR(64)   NOT NULL,
    author_user_id            BIGINT        REFERENCES users(id),
    author_username           VARCHAR(64),
    description               VARCHAR(512),
    reason                    CLOB,                          -- may link to incident ID
    applied_at                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    apply_duration_ms         INT,
    apply_result              VARCHAR(16)   NOT NULL,        -- success | failed | rolled_back
    reload_impact_json        CLOB,                          -- JSON: { channel, connections_drained }
    rolled_back_from_version  INT,                           -- source version if this is a rollback
    is_milestone              BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_file_version UNIQUE(file_name, version)
);

CREATE INDEX idx_config_file_ver ON config_versions(file_name, version DESC);


-- ---------------------------------------------------------------------------
-- sessions
-- Active JWT sessions. Revocation is done by setting revoked=TRUE.
-- jti (JWT ID) is the primary key.
-- ---------------------------------------------------------------------------
CREATE TABLE sessions (
    id           VARCHAR(64)  PRIMARY KEY,        -- JWT jti (UUID)
    user_id      BIGINT       NOT NULL REFERENCES users(id),
    issued_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at   TIMESTAMP    NOT NULL,
    revoked      BOOLEAN      NOT NULL DEFAULT FALSE,
    source_ip    VARCHAR(64)
);

CREATE INDEX idx_sessions_user    ON sessions(user_id);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);


-- ---------------------------------------------------------------------------
-- Seed: default administrator.
-- BCrypt hash below is for password "changeme" (cost 10, $2a$ prefix).
-- Verified with Spring Security BCryptPasswordEncoder.
-- The must_change_password flag forces a password change on first login.
-- ---------------------------------------------------------------------------
INSERT INTO users (username, password_hash, role, status, must_change_password)
VALUES (
    'admin',
    '$2a$10$ntai2tksL.fH3Ca.Ox6OcO7lYVAKj8NG26fgFgxMUf82gm8gEEuwK',
    'admin',
    'active',
    TRUE
);
