cluster {
    cluster-name = ""
    jgroup-path = ""

    role {
        prefer = ""
        strict = false
    }

    members = []

    jgroup {
        bind-addr = ""
        port = 0
    }

    hazelcast {
        port = 0
        network-interface = ""
        map-backup-count = 0
        map-async-backup-count = 0
    }

    failover {
        failover-timeout = 0
        split-brain-policy = ""
        quorum-size = 0
    }
}
