# TCP Config for fello
channel {
    name fello1
    type tcp

    server {
        listen 13.131.9.162 36000
        pool 13.131.9.171
    }

    client {
        connect 13.131.9.162 36021 weight 100 priority 1 
        connect 13.131.9.166 36021 weight 100 priority 1
#        connect 13.131.9.167 36024 weight 100 priority 1
        strategy roundrobin
    }

    profile iso8583
}


channel {
    name finnet
    type tcp

    server {
        listen 13.131.9.162 36001
#        pool 10.132.130.138  weight 100 priority 0
        pool 13.131.9.171 weight 100 priority 1
	strategy roundrobin
    }

    client {
        connect 13.131.9.162 36025 weight 100 priority 1
        connect 13.131.9.166 36025 weight 100 priority 1
 #       connect 13.131.9.167 36025 weight 100 priority 1
        strategy roundrobin
    }

    profile iso8583
}

profile iso8583 {
    direction inbound {
        de1 in ["0800", "0200", "0420", "0421"]
    }

    direction outbound {
        de1 in ["0810", "0210", "0430"]
    }

    correlation {
        de2
        de11
        de37
        de13
        de12
    }
}
